version: '2'
services:
  squid:
    image: procube/squid-bump-ssl:latest
    container_name: squid
    ports:
      - "3128:3128"
    volumes:
      - "${HIVE_CONTEXT_DIR}/ca/cacert.pem:/etc/squid/cert/bump.crt"
      - "${HIVE_CONTEXT_DIR}/ca/cakey.pem:/etc/squid/cert/bump.key"
      - squid_cache:/var/spool/squid
      - squid_ssldb:/var/lib/squid/ssl_db
      - squid_log:/var/log/squid
      - squid_config:/etc/squid
  nginx:
    build: nginx
    container_name: nginx
  registry:
    image: registry
    container_name: registry
    volumes:
      - registry:/var/lib/registry
      - registry_config:/etc/docker/registry
    environment:
      - REGISTRY_HTTP_HOST="http://registry-mirror.offline-cache"
volumes:
  squid_cache:
  squid_ssldb:
  squid_log:
  squid_config:
  registry:
  registry_config:
  auth:
